### ISSUE TITLE
Certificate length Comparison in Tabular data

### ISSUE THREAD

**Issue by anilbatra2185** [egoschema/EgoSchema#5]
hi,

thanks for sharing the great work!

I wonder if there is a tabular data (with exact numbers) for Figure 3 in the main paper. Additionally, how many videos/samples are used to compute the certificate length. I can see that the EgoSchema uses 100 videos, however, the exact number of videos from other datasets is helpful.

**Comment by egoschema** [comment]
Hello!

For different datasets, it took different amounts of videos. Since the QA datasets do not have classes we ensured at least two hours of human effort is applied, so depending on the datasets it was varying from 50 videos to 100 videos. Here is the exact numbers attached in the CSV file.  
[cert (1).csv](https://github.com/egoschema/EgoSchema/files/13665572/cert.1.csv)

**Comment by TousakaNagio** [comment]
Hello @egoschema ,

Can I refer the data in the cert(1).csv file in my publication? Thanks!
