### ISSUE TITLE
How to establish correspondence between EgoSchema IDs and Ego4D video/clip IDs?

### ISSUE THREAD

**Issue by reddyav1** [egoschema/EgoSchema#7]
Thanks for releasing this great benchmark!

Could you provide some guidance on how to establish correspondence between EgoSchema IDs and the IDs of the original Ego4D video/clip from which the sample is derived?

I see a similar question was asked in #4, and a mapping between EgoSchema ID and scenario was provided. I'd be looking for a more specific mapping to Ego4D ID. Thanks!

**Comment by reddyav1** [comment]
In addition to the above mapping, it would also be great if we could get timestamp information for aligning the EgoSchema videos with the original Ego4D videos.

**Comment by egoschema** [comment]
I am very sorry for the late reply. I am not sure if I can share this information right now since giving out the exact Ego4d video and timestamps would allow people to gather the actual narrations connected to the video and it would allow some people to cheat the benchmark that is supposed to visual.

**Comment by afourast** [comment]
Could you then please supply just the list of Ego4D videos covered by the dataset, without mappings? Also the subset of Ego4D videos covered by the 500 open QAs. Those would enable people to pre-train on Ego4D without feat of train-test contamination
